### ISSUE TITLE
Send events when the user closes the App

### ISSUE THREAD

**Issue by omzer** [claimsforce-gmbh/flutter-segment#103]
Segment is not sending the events immediately (understandably to save up on battery), but that means the App will lose some important events if the user killed the App before these events are sent.

Common scenario would be:
- User installs the App.
- Try to log in.
- Fail for some reason (track the email and reason and send event).
- Closes the App and maybe uninstall it.

This is very critical stage of the App that I cannot track, **any help?**

And thank for the great work on the library :)

**Comment by MaiKaY** [comment]
Hi @omzer,
thanks for raising this issue but this is not the right place, since this library is "just" a flutter wrapper around the segment SDK and we don't have influence how data/events are sent to segment. You should raise this issue in one of the concrete SDK implementations.

- [iOS](https://github.com/segmentio/analytics-ios)
- [Android](https://github.com/segmentio/analytics-android)
