### ISSUE TITLE
Some props doesn't work

### ISSUE THREAD

**Issue by iampawan** [claimsforce-gmbh/flutter-segment#23]
Some props like "token", "username" doesn't work. Is there any reserved list for keywords that are not supposed to be the custom properties?

**Comment by MaiKaY** [comment]
Hi @iampawan,
since we are using the native segment libraries under the hood I would like to ask you if you could create this kind of request directly in one of the segment repos at GitHub.

- [Segment iOS](https://github.com/segmentio/analytics-ios/issues/new)
- [Segment Android](https://github.com/segmentio/analytics-android/issues/new)

Thanks.
